server {
    # Nginx escucha peticiones en el puerto 80 dentro del contenedor
    listen 4200;
    
    # Directorio raíz donde Nginx buscará los archivos estáticos
    root /usr/share/nginx/html;
    
    # Define el archivo de inicio
    index index.html index.htm;

    # Bloque de ubicación principal
    location / {
        # Configuración esencial para SPAs como React
        # 1. Intenta servir el archivo solicitado ($uri)
        # 2. Si no es un archivo, intenta servirlo como directorio ($uri/)
        # 3. Si no encuentra nada, redirige internamente a /index.html 
        #    (Esto permite que React Router maneje las rutas)
        root   /usr/share/nginx/html/www/mimirapp/;
        try_files $uri $uri/ /index.html;
         index  index.html index.htm;
    }

    # Descomenta este bloque si necesitas manejo de errores 404/500 personalizado
    # error_page 500 502 503 504 /50x.html;
    # location = /50x.html {
    #     root /usr/share/nginx/html;
    # }
}